### ISSUE TITLE
Got this error when Colors is pressed after using Fragment Class

### ISSUE THREAD

**Issue by Codefeak** [udacity/ud839_Miwok#53]
11-02 19:12:55.755 1545-1591/com.example.android.miwok D/AppTracker: App Event: stop
11-02 19:12:55.779 1545-1545/com.example.android.miwok V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@3ca35be
11-02 19:12:55.779 1545-1545/com.example.android.miwok V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@86cf61f
11-02 19:12:55.803 1545-1545/com.example.android.miwok D/AndroidRuntime: Shutting down VM
11-02 19:12:55.803 1545-1545/com.example.android.miwok E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.example.android.miwok, PID: 1545
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.miwok/com.example.android.miwok.ColorsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)' on a null object reference
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2733)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819)
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6321)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)' on a null object reference
                                                                             at com.example.android.miwok.ColorsFragment.onCreateView(ColorsFragment.java:179)
                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                             at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                             at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
                                                                             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
                                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1322)
                                                                             at android.app.Activity.performStart(Activity.java:6777)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2696)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819) 
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:154) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6321) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
11-02 19:12:55.803 1545-1545/com.example.android.miwok D/AppTracker: App Event: crash

**Comment by Kvaibhav01** [comment]
You need to be more specific. How can one read such a huge logcat? 😕

**Comment by Codefeak** [comment]
FATAL EXCEPTION: main Process: com.example.android.miwok, PID: 1545
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.miwok/com.example.android.miwok.ColorsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)'

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)' on a null object reference
at com.example.android.miwok.ColorsFragment.onCreateView(ColorsFragment.java:179)

I don't know how to be more specific

**Comment by xinkev** [comment]
As the logcat says, you are getting NullPointerException because of the Object that you are invoking the setAdapter method on, seems to be Null. Which means the object doesn't have a value or any property.  Hope it helps.

**Comment by Kvaibhav01** [comment]
_[java.lang.NullPointerException](https://developer.android.com/reference/java/lang/NullPointerException.html)_ means you called the instance method of a null object.

It may be **because you forgot to initialize or you initialized a variable with a null value**. Try providing some code of your main activity.
