### ISSUE TITLE
Plugin with id 'com.android.application' not found.

### ISSUE THREAD

**Issue by singhdeepansh** [udacity/ud839_Miwok#87]
i am getting this error while i am gradle is syncing

**Comment by Kvaibhav01** [comment]
Make sure your Gradle version is compatible with your Android Gradle Plugin. 

If your project level build.gradle says:

```
buildscript {
    repositories {
        google() 
    }
```
Then the Gradle version is 4.0 and above. If it's like this:

```
buildscript {
    repositories {
        maven { url "https://maven.google.com" } 
    }
```
Then the Gradle version is less than 4.0.

Just correct this and sync your project with Gradle.

If still, the error persists then find the _gradle-wrapper.properties_ file and change the last sentence to this:
`distributionUrl=http\://services.gradle.org/distributions/gradle-2.2.1-all.zip`

Note that the Gradle version in the above line must match with the one you have in your _build.gradle_  file.

**Comment by amit13091992** [comment]
Try adding the latest Gradle dependency in your project-level build.gradle file:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        **classpath 'com.android.tools.build:gradle:2.1.2'**   //change this with latest gradle version.
    }
} 

allprojects {
    repositories {
        jcenter()
    }
}
```

And do sync gradle once after doing this, it will work.

**Comment by WeBeCreativeCanada** [comment]
I'm getting the same error but have applied the above fix so hoping for some feedback on what I have implementated below: 
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.0.1'

        classpath 'com.google.gms:google-services:4.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir

**Comment by amit13091992** [comment]
@WebeCreativeCanada

Have u added this line too?

**classpath 'com.android.tools.build:gradle:2.1.2'**   //change this with latest gradle version.

**Comment by WeBeCreativeCanada** [comment]
Added them like this:
    dependencies {
        classpath 'com.google.gms:google-services:4.0.1'

        classpath 'com.google.gms:google-services:4.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**Comment by amit13091992** [comment]
> Added them like this:
> dependencies {
> classpath 'com.google.gms:google-services:4.0.1'
> 
> ```
>     classpath 'com.google.gms:google-services:4.0.1'
>     // NOTE: Do not place your application dependencies here; they belong
>     // in the individual module build.gradle files
> }
> ```
> 
> }

You need to add build tools for gradle too for syncing the project. check my answer once.
After you will add this and still getting this error then do:
**clean**   **rebuild** and after that **invalidate cache/Restart**.

**Comment by WeBeCreativeCanada** [comment]
Now I am getting this error:
Could not find method classpath() for arguments [com.google.gms:google-services:4.0.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by WeBeCreativeCanada** [comment]
![Screen Shot 2019-04-29 at 1 52 40 PM](https://user-images.githubusercontent.com/49915849/56916177-4b1f1180-6a86-11e9-9e22-b186b0b890b4.png)
That is the structure and things have changed since 2015

**Comment by amit13091992** [comment]
Add maven { url "https://maven.google.com" } to your root level build.gradle file

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}
This maven repo is required starting from 11.2.0.

You can also use the google() shortcut but check the requirements before using it.

Firebase Android SDKs and Google Play Services libraries now have independent version numbers, allowing for more frequent, flexible updates. Update the google play service gradle plugin version to the latest version (at least 3.3.1).

classpath 'com.google.gms:google-services:4.0.1'

**and update the libraries to the latest version.**

> ![Screen Shot 2019-04-29 at 1 52 40 PM](https://user-images.githubusercontent.com/49915849/56916177-4b1f1180-6a86-11e9-9e22-b186b0b890b4.png)
> That is the structure and things have changed since 2015

**Comment by sag-007** [comment]
![androidstudio](https://user-images.githubusercontent.com/44050943/81523217-da822480-936a-11ea-8ae7-df5e3d8bb6f3.PNG)

Plugin with id 'com.android.application' not found.
what should i do ?

**Comment by amit13091992** [comment]
> ![androidstudio](https://user-images.githubusercontent.com/44050943/81523217-da822480-936a-11ea-8ae7-df5e3d8bb6f3.PNG)
> 
> Plugin with id 'com.android.application' not found.
> what should i do ?

Check once your Mainactivity.java file I think it might have any error and once do:
1. Gradle sync
2. Invalidate cache and restart in Android studio

**Comment by sag-007** [comment]
Process: com.example.final_project, PID: 2305
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.final_project/com.example.final_project.SignIn}: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@d9ee1b9 rejected from com.google.firebase.database.core.utilities.DefaultRunLoop$1@382a9fe[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7099)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@d9ee1b9 rejected from com.google.firebase.database.core.utilities.DefaultRunLoop$1@382a9fe[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2085)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:654)
        at com.google.firebase.database.core.utilities.DefaultRunLoop.scheduleNow(com.google.firebase:firebase-database@@16.0.4:105)
        at com.google.firebase.database.core.Repo.scheduleNow(com.google.firebase:firebase-database@@16.0.4:276)
        at com.google.firebase.database.Query.addEventRegistration(com.google.firebase:firebase-database@@16.0.4:233)
        at com.google.firebase.database.Query.addValueEventListener(com.google.firebase:firebase-database@@16.0.4:149)
        at com.example.final_project.SignIn.updateUsers(SignIn.java:53)
        at com.example.final_project.SignIn.onCreate(SignIn.java:48)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7099) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
how can i solve it ?this is from logcat

I am getting the above error when I  try to installl my application ? And it says myappname Keeps stoping

**Comment by SudKul** [comment]
The issue is due to compatibility between Gradle version and Android Gradle Plugin.
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies. 

Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.

**Comment by Bipulpavsk** [comment]
![image](https://user-images.githubusercontent.com/53951722/169242658-fb65ee3d-1c00-4b20-bdc1-7691ef6fbd17.png)


Please help me on this i am getting an error while sync the gradles
